services:
  - type: web
    name: receipt-detector
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
build:
  installCommand: |
    apt-get update && \
    apt-get install -y tesseract-ocr tesseract-ocr-heb tesseract-ocr-eng && \
    pip install -r requirements.txt
